#This file builds the Docker images for a React/NodeJS application and runs it as microservices on Docker containers

#To ensure successful execution, clone this entire repository and execute this file while in the root folder of the cloned repository

#It's also a requirement to have Docker and the docker-compose plugin installed in your environment

#To launch this app without having to clone the entire repository,use the docker-compose.yaml file to run the app

version: "3.8"

services:

  #Builds the frontend Docker image and creates the frontend microservice
  brian-yolo-client:
    container_name: brian-yolo-client
    image: brianbwire/brian-yolo-client:v1.0.1
    build: ./client
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on: 
      - brian-yolo-backend
    networks:
      - yolo-net

  #Builds the backend Docker image and creates the backend microservice
  brian-yolo-backend:
    container_name: brian-yolo-backend
    image: brianbwire/brian-yolo-backend:v1.0.1
    build: ./backend
    stdin_open: true
    tty: true
    restart: always
    ports:
      - "5000:5000"
    depends_on: 
      - yolo-ip-mongo
    networks:
      -yolo-net

  #Creates the database microservice
  yolo-ip-mongo:
    image: mongo
    container_name: yolo-mongo
    ports:
      - "27017:27017"
    networks:
      - yolo-net
    volumes:
      - type: volume
        source: yolo-mongo-data
        target: /data/db

#Creates the network infrastructure necessary for the containers to communicate with each other
networks:
  yolo-net:
    name: yolo-net
    driver: bridge
    attachable: true
    ipam:
      config:
        - subnet: 172.20.0.0/16 
          ip_range: 172.20.0.0/16 

#Creates a Docker volume that persists all the data stored in the database
volumes:
  yolo-mongo-data:
    driver: local