---
- name: Pull image from repository
  docker_image:
    name: "{{ backend_image }}"
    source: pull

- name: Create Node.js Backend Container
  community.docker.docker_container:
    name: "{{ backend_container_name }}"
    image: "{{ backend_image }}"
    networks:
      - name: "{{ backend_network }}"
    ports:
      - "5000:5000"
    volumes:
     - "{{ backend_volume }}"
    env:
      MONGODB_URI: "mongodb://yolo-ip-mongo:27017/yolomy"
      PORT: "5000"
    command: "npm start"
    restart_policy: always
  become: yes